import turtle
turtle.showturtle()
turtle.speed(10)

turtle.circle(50)
turtle.penup()
turtle.goto(60, 40)
turtle.right(180)
turtle.pendown()
turtle.circle(50)
turtle.penup()
turtle.goto(120, 0)
turtle.right(180)
turtle.pendown()
turtle.circle(50)
turtle.penup()
turtle.goto(-60, 40)
turtle.right(180)
turtle.pendown()
turtle.circle(50)
turtle.penup()
turtle.goto(-120, 0)
turtle.right(180)
turtle.pendown()
turtle.circle(50)

turtle.done()