import turtle
turtle.showturtle()
turtle.speed(10)
turtle.bgcolor("blue")

turtle.fillcolor("white")
turtle.begin_fill()
turtle.right(45)
turtle.forward(70)
turtle.right(135)
turtle.forward(100)
turtle.right(135)
turtle.forward(70)
turtle.end_fill()
turtle.right(90)
turtle.forward(70)
turtle.left(155)
turtle.forward(150)
turtle.left(141)
turtle.forward(150)

turtle.done()