import turtle
turtle.showturtle()
turtle.speed(10)

turtle.fillcolor("black")
turtle.goto(0, -2.5)
turtle.begin_fill()
turtle.circle(5)
turtle.end_fill()

for x in range (2):
    turtle.goto(0, 0)
    turtle.pendown()
    turtle.right(45)
    turtle.forward(100)
    turtle.backward(2.5)
    turtle.right(90)
    turtle.begin_fill()
    turtle.circle(5)
    turtle.end_fill()
    turtle.left(90)
    turtle.forward(2.5)
    turtle.right(135)
    turtle.forward(25)
    turtle.penup()
    turtle.forward(15)
    turtle.pendown()
    turtle.forward(25)
    turtle.penup()
    turtle.forward(15)
    turtle.pendown()
    turtle.forward(25)
    turtle.penup()
    turtle.forward(15)
    turtle.pendown()
    turtle.forward(25)
    turtle.penup()

turtle.left(90)

for x in range (2):
    turtle.goto(0, 0)
    turtle.pendown()
    turtle.right(45)
    turtle.forward(100)
    turtle.backward(2.5)
    turtle.right(90)
    turtle.begin_fill()
    turtle.circle(5)
    turtle.end_fill()
    turtle.left(90)
    turtle.forward(2.5)
    turtle.right(135)
    turtle.forward(150)
    turtle.penup()

turtle.done()
