import turtle
turtle.showturtle()
turtle.speed(0)
turtle.bgcolor("dark blue")
screensize = turtle.Screen()
screensize.setup(width=1200, height=600)

turtle.left(90)

def UnionWhite():
    turtle.penup()
    turtle.goto(0, 150)
    turtle.fillcolor("white")
    turtle.begin_fill()
    turtle.forward(35)
    turtle.left(90)
    turtle.forward(600)
    turtle.left(90)
    turtle.forward(70)
    turtle.left(90)
    turtle.forward(600)
    turtle.left(90)
    turtle.forward(35)
    turtle.goto(-265, 150)
    turtle.forward(150)
    turtle.left(90)
    turtle.forward(70)
    turtle.left(90)
    turtle.forward(300)
    turtle.left(90)
    turtle.forward(70)
    turtle.left(90)
    turtle.forward(150)
    turtle.end_fill()
    turtle.goto(-600, 300)
    turtle.begin_fill()
    turtle.right(90)
    turtle.forward(100)
    turtle.right(30)
    turtle.forward(250)
    turtle.right(150)
    turtle.forward(150)
    turtle.right(30)
    turtle.forward(250)
    turtle.left(30)
    turtle.end_fill()
    turtle.goto(0, 0)
    turtle.begin_fill()
    turtle.forward(100)
    turtle.right(30)
    turtle.forward(250)
    turtle.right(150)
    turtle.forward(150)
    turtle.right(30)
    turtle.forward(190)
    turtle.right(60)
    turtle.forward(30)
    turtle.end_fill()
    turtle.goto(-600, 0)
    turtle.begin_fill()
    turtle.left(90)
    turtle.forward(100)
    turtle.left(30)
    turtle.forward(250)
    turtle.left(150)
    turtle.forward(150)
    turtle.left(30)
    turtle.forward(190)
    turtle.left(60)
    turtle.forward(30)
    turtle.end_fill()
    turtle.goto(0, 300)
    turtle.begin_fill()
    turtle.right(90)
    turtle.forward(100)
    turtle.left(30)
    turtle.forward(250)
    turtle.left(150)
    turtle.forward(150)
    turtle.left(30)
    turtle.forward(190)
    turtle.left(60)
    turtle.forward(30)
    turtle.end_fill()

def UnionRed():
    turtle.penup()
    turtle.goto(0, 150)
    turtle.fillcolor("red")
    turtle.begin_fill()
    turtle.forward(25)
    turtle.left(90)
    turtle.forward(600)
    turtle.left(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(600)
    turtle.left(90)
    turtle.forward(25)
    turtle.goto(-275, 150)
    turtle.forward(150)
    turtle.left(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(300)
    turtle.left(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(150)
    turtle.end_fill()
    turtle.goto(-600, 300)
    turtle.begin_fill()
    turtle.right(120)
    turtle.forward(225)
    turtle.right(150)
    turtle.forward(30)
    turtle.right(30)
    turtle.forward(250)
    turtle.right(150)
    turtle.forward(10)
    turtle.end_fill()
    turtle.goto(0, 0)
    turtle.begin_fill()
    turtle.left(180)
    turtle.right(30)
    turtle.forward(225)
    turtle.right(150)
    turtle.forward(30)
    turtle.right(30)
    turtle.forward(190)
    turtle.right(60)
    turtle.forward(10)
    turtle.end_fill()
    turtle.goto(-530, 0)
    turtle.begin_fill()
    turtle.right(180)
    turtle.right(60)
    turtle.forward(220)
    turtle.left(150)
    turtle.forward(30)
    turtle.left(30)
    turtle.forward(220)
    turtle.left(150)
    turtle.forward(10)
    turtle.end_fill()
    turtle.goto(-70, 300)
    turtle.begin_fill()
    turtle.right(90)
    turtle.right(60)
    turtle.forward(220)
    turtle.left(150)
    turtle.forward(30)
    turtle.left(30)
    turtle.forward(220)
    turtle.left(150)
    turtle.forward(10)
    turtle.end_fill()

UnionWhite()
UnionRed()

def star(size, sides):
    turtle.pencolor("white")
    turtle.fillcolor("white")
    turtle.begin_fill()
    for x in range (sides):
        turtle.forward(size)
        angle = 180.0 - 180.0 / sides
        turtle.right(angle)
    turtle.end_fill()

turtle.penup()
turtle.goto(300, -200)
turtle.pendown()
star(100, 7)
turtle.penup()
turtle.left(180)
turtle.goto(350, 0)
turtle.pendown()
star(30, 5)
turtle.penup()
turtle.left(180)
turtle.goto(450, 100)
turtle.pendown()
star(60, 7)
turtle.penup()
turtle.goto(300, 200)
turtle.pendown()
star(60, 7)
turtle.penup()
turtle.goto(150, 50)
turtle.pendown()
star(60, 7)
turtle.penup()
turtle.goto(-225,-150)
turtle.pendown()
star(150, 7)

turtle.done()