import turtle
turtle.showturtle()
turtle.speed(0)
turtle.bgcolor("dark blue")
screensize = turtle.Screen()
screensize.setup(width=1200, height=600)

X = [-600, 0, -600, 0]
Y = [300, 0, 0, 300]
Rotation = [90, -90, -90, 90]

turtle.left(90)
turtle.penup()

def UnionWhite():
    turtle.goto(0, 185)
    turtle.fillcolor("white")
    turtle.begin_fill()
    for x in range (2):
        turtle.left(90)
        turtle.forward(600)
        turtle.left(90)
        turtle.forward(70)
    turtle.end_fill()
    turtle.goto(-265, 300)
    turtle.begin_fill()
    for x in range (2):
        turtle.left(90)
        turtle.forward(70)
        turtle.left(90)
        turtle.forward(300)
    turtle.end_fill()
    ArrayValue = 0
    for x in range (2):
        turtle.goto(X[ArrayValue], Y[ArrayValue])
        turtle.right(Rotation[ArrayValue])
        turtle.begin_fill()
        turtle.forward(100)
        turtle.right(30)
        turtle.forward(250)
        turtle.right(150)
        turtle.forward(150)
        turtle.right(30)
        turtle.forward(190)
        turtle.right(60)
        turtle.forward(30)
        turtle.end_fill()
        ArrayValue = ArrayValue + 1
    for x in range (2):
        turtle.goto(X[ArrayValue], Y[ArrayValue])
        turtle.right(Rotation[ArrayValue])
        turtle.begin_fill()
        turtle.forward(100)
        turtle.left(30)
        turtle.forward(250)
        turtle.left(150)
        turtle.forward(150)
        turtle.left(30)
        turtle.forward(190)
        turtle.left(60)
        turtle.forward(30)
        turtle.end_fill()
        ArrayValue = ArrayValue + 1

def UnionRed():
    turtle.goto(0, 175)
    turtle.fillcolor("red")
    turtle.begin_fill()
    for x in range (2):
        turtle.left(90)
        turtle.forward(600)
        turtle.left(90)
        turtle.forward(50)
    turtle.end_fill()
    turtle.goto(-275, 300)
    turtle.begin_fill()
    for x in range (2):
        turtle.left(90)
        turtle.forward(50)
        turtle.left(90)
        turtle.forward(300)
    turtle.end_fill()
    turtle.goto(-600, 300)
    turtle.begin_fill()
    turtle.right(120)
    turtle.forward(225)
    turtle.right(150)
    turtle.forward(30)
    turtle.right(30)
    turtle.forward(250)
    turtle.right(150)
    turtle.forward(10)
    turtle.end_fill()
    turtle.goto(0, 0)
    turtle.begin_fill()
    turtle.left(180)
    turtle.right(30)
    turtle.forward(225)
    turtle.right(150)
    turtle.forward(30)
    turtle.right(30)
    turtle.forward(190)
    turtle.right(60)
    turtle.forward(10)
    turtle.end_fill()
    turtle.goto(-530, 0)
    turtle.begin_fill()
    turtle.right(180)
    turtle.right(60)
    turtle.forward(220)
    turtle.left(150)
    turtle.forward(30)
    turtle.left(30)
    turtle.forward(220)
    turtle.left(150)
    turtle.forward(10)
    turtle.end_fill()
    turtle.goto(-70, 300)
    turtle.begin_fill()
    turtle.right(90)
    turtle.right(60)
    turtle.forward(220)
    turtle.left(150)
    turtle.forward(30)
    turtle.left(30)
    turtle.forward(220)
    turtle.left(150)
    turtle.forward(10)
    turtle.end_fill()

def star(size, sides):
    turtle.pencolor("white")
    turtle.fillcolor("white")
    turtle.begin_fill()
    for x in range (sides):
        turtle.forward(size)
        angle = 180.0 - 180.0 / sides
        turtle.right(angle)
    turtle.end_fill()

UnionWhite()
UnionRed()
turtle.goto(350, -200)
star(100, 7)
turtle.left(180)
turtle.goto(400, 0)
star(30, 5)
turtle.left(180)
turtle.goto(500, 100)
star(60, 7)
turtle.goto(350, 200)
star(60, 7)
turtle.goto(200, 50)
star(60, 7)
turtle.goto(-225,-150)
star(150, 7)

turtle.done()